#!/bin/bash
read -p "Enter your name: " name
read -p "Enter your age: " age
read -p "Enter your expactation: " average
if [[ $age -le 18 ]]
then
        echo " Student"
        echo " At least $(( 18 - $age )) years to become a worker"
elif [[ $age -gt 18 ]] && [[ $age -le 65 ]]
then
        echo " Worker"
        echo " $(( 65 - $age)) to retire"
elif [[ $age -gt 65 ]]
then
        if [[ $age -le $average ]]
        then
                echo " Retired"
                echo " $(( $average - $age )) to die"
        else
                echo -ne \007
                echo " !!! Already Died !!! "
                sleep 1
                echo " !!! Already Died !!! "
                sleep 2
                echo " !!! Already Died !!! "
fi
fi
